language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t xardas88/docker-react -f Dockerfile.dev .

script:
      - docker run -e CI=true xardas88/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker4"
  env: "Docker4-env"
  bucket_name: "elasticbeanstalk-eu-north-1-188944998131"
  bucket_path: "docker4"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY